---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    keepass_database: "/root/CI_CD_Database.kdbx"
    keepass_password: "ansible"
  tasks:
    - name: Test KeePass Entry Module
      ansible.builtin.import_tasks: tasks/entry_tasks.yml

    - name: Test KeePass Group Module
      ansible.builtin.import_tasks: tasks/group_tasks.yml
