name: CI Pipeline

on: [push, pull_request]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   name: Ansible Lint
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install ansible ansible-lint yamllint
  #     - name: Run ansible-lint
  #       run: ansible-lint .
  #     - name: Run yamllint
  #       run: yamllint .

  molecule:
    runs-on: ubuntu-latest
    name: Molecule Test
    services:
      docker:
        image: docker:20.10.24
        options: --privileged
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo systemctl start docker
      #     sudo systemctl enable docker
      #     sudo usermod -aG docker $USER

      - name: Install test dependencies.
        run: pip3 install docker ansible molecule-plugins[docker] yamllint ansible-lint pykeepass


      # - name: Checkout code
      #   uses: actions/checkout@v2
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.11'
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-pip
      #     pip install ansible
      #     pip3 install molecule[docker] pykeepass
      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
